apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ZW5KdmMzTnBlanBuYUhCZloyNWFka3AwT1V4UFoycE5PVVJXVmtSbVRXSnRaa3B3TWs5bWIzQkpNMWhHZUV3MQ==
type: kubernetes.io/dockerconfigjson
